### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by samcdavid** [spartansystems/booster-kit-phoenix#36]
When a user hits the api from a browser, a favicon cannot be found. This generates a really ugly error that should not be generated:

> #PID<0.350.0> running WebDelivery.Endpoint terminated
Server: phoenix-booster-kit.herokuapp.com:80 (http)
Request: GET /favicon.ico
** (exit) an exception was raised: ...

This error needs to be resolved in the Phoenix Booster Kit so that superfluous things (such as favicons) do not cause errors.

[Rollbar Error](https://rollbar.com/Spartan/booster-kit-phoenix/items/2/)

**Comment by samcdavid** [comment]
@endersstocker do you think this is an issue we need to worry about? I've been searching this for a while and its an issue if you hit the API through the browser. I think the only way to fix the error is to actually provide a favicon, but if you don't hit the api through the browser then it isn't a problem.

**Comment by endersstocker** [comment]
@samcdavid Does it actually raise an exception in production with the static plug removed? It should just generate a 404 for that resource.

**Comment by samcdavid** [comment]
@endersstocker It does just raise a 404. It is annoying but I did some research and there is nothing we can do about it other than add a favicon, which seems silly for a backend api that should not be hit through the browser.
